### ISSUE TITLE
Manually adding a WiFi network bug

### ISSUE THREAD

**Issue by MikeCedonis** [mrfixit2001/recalbox_rockpi4#2]
I have my network hidden and tried to manually add it and got a long rectangular input field which I couldn't type into with a keyboard. Upon cancelling and going back the virtual keyboard finally showed. I decided to see if it would happen again by cancelling and it went back to no virtual keyboard. After the above, I decided to connect to an SSID in the wifi list and I couldn't get out of the screen until I Ctrl+alt+del to restart.

**Comment by MikeCedonis** [comment]
Don't know whether to create a separate issue but the IP address shown is in hex.

**Comment by mrfixit2001** [comment]
Thanks for reporting the issue! This is actually a problem from Recalbox themselves, and I'm waiting for them to fix it. But you found the work around, simply close and return and the keyboard shows up. 

Also, if your IP address is showing as hex, then it may be because you are not successfully connected to your wireless connection. I have found these wifi/bt combo chips sometimes don't like 5ghz networks.

**Comment by MikeCedonis** [comment]
Didn't know it was bug in recalbox itself(first time using it) and thanks for the tip on the 5ghz, I had to switch to Ethernet for it to connect properly to the network and transfer files. 
Thanks!

**Comment by mrfixit2001** [comment]
Updated release coming under my new recalbox-rockchip repo. I'll be sure to test Wifi before pushing it.
