### ISSUE TITLE
Recalbox doesn't boot on RockPi4

### ISSUE THREAD

**Issue by jyapayne** [mrfixit2001/recalbox_rockpi4#4]
In order to get the image to boot, I have to remove `video=HDMI-A-1:1920x1080@60` from the extlinux.conf file. However, the graphics are then not using 1080p and the boot video is way off screen. Also, no controllers that I have work (Logitech F310, Xbox360 wired). Any advice on changing the video field to work?

**Comment by mrfixit2001** [comment]
Hey! So I haven't heard of anyone else with this issue, but if you plug into a monitor that doesn't support 1080p or 60fps then you would run into a display issue. It will still boot but the video being output wouldn't show if the monitor doesn't support that mode. Recalbox designed their boot videos for 1080p, that's why they don't show full screen when you remove that parameter. Without it, the kernel should auto select whatever the maximum resolution detected that your monitor supports, and emulationstation will also render at that same detected resolution. You will want to try a different HDMI cable and a different monitor as well. Let me know how it goes. It shouldn't be a software issue.

**Comment by mrfixit2001** [comment]
I haven't heard of any issues with the controllers yet either... i know Xbox controllers work, and all USB controllers I've tested have worked. What's the DMESG look like? It should show you what they are detected as when you plug them in.

**Comment by jyapayne** [comment]
I managed to fix the controller issue (it turns out my SD card was corrupted, so I imaged a different one).

For the HDMI, it still won't show on screen if I have that video parameter in the extlinux.conf after setting up a new SD card. However, when I remove it, the boot sequence is still off-screen partially, but the menu itself and emulators are all in 1080p. Unfortunately, I only have one monitor and HDMI cable to test on.

**Comment by mrfixit2001** [comment]
Glad you got most of it sorted out! Makes me wonder what resolution you're seeing during the boot sequence. Definitely bigger than 1080p if the boot video is small and in the corner, as that's sized for 1080p. But since you've got it working, ok to close the issue?

**Comment by MikeCedonis** [comment]
Try setting "global.videomode" to "DMT 35 : 1280x1024@60" if you aren't using a TV
